### PR TITLE
Add a converter that finds gist URLs and converts these to gist shortcodes for Hugo

### PR DESCRIPTION
**Pull request by lawrencegripper**

### CODE REVIEW

**Review by ashishb — APPROVED** [review]
Thanks for the contribution.

**Comment by ashishb** [comment]
@lawrencegripper did you mistakenly marked this as a `draft`?

**Comment by lawrencegripper** [comment]
> Thanks for the contribution.

No worries thanks for the tool, it's awesome. 

> @lawrencegripper did you mistakenly mark this as a draft?

I'm still testing it out on my blog that I'm migrating. I've hit a few other entries where I use `[gist URL]` and trying to handle those too.

**Comment by lawrencegripper** [comment]
:crossed_fingers: this is good to go, it now handles gists that where added with new block editor and gists added with the old markdown syntax 

```
<figure class="wp-block-embed is-type-rich is-provider-embed-handler wp-block-embed-embed-handler"><div class="wp-block-embed__wrapper">
https://gist.github.com/lawrencegripper/8e701b0d201e65af0f8bc9b8b0b14207
</div></figure>

AND

<body>
some text
\[gist https://gist.github.com/lawrencegripper/6bee7de123bea1936359\]
some more text
</body>
```

**Comment by ashishb** [comment]
@lawrencegripper there are a few linter issues before this can be merged in

```
Running [/home/runner/golangci-lint-1.60.3-linux-amd64/golangci-lint run --path-prefix=src/wp2hugo] in [/home/runner/work/wp2hugo/wp2hugo/src/wp2hugo] ...
  Error: src/wp2hugo/internal/hugogenerator/hugopage/html_to_markdown_converter.go:129:6: func `handleBlockEditorImages` is unused (unused)
  func handleBlockEditorImages() md.Plugin {
       ^
  Error: src/wp2hugo/internal/hugogenerator/hugopage/html_to_markdown_converter_test.go:31:7: const `_textBlockEditorImg` is unused (unused)
  const _textBlockEditorImg = `
        ^
  Error: issues found
```

Ref: https://github.com/ashishb/wp2hugo/actions/runs/10709341180/job/29693758685?pr=39

**Comment by lawrencegripper** [comment]
I hit an issue with `img`'s that where added view the new block editor. The `src` has `?w=1024` appended which causes the file downloaded to be `image.png?w=1024` and this doesn't work with `hugo serve`. 

image

I've used a similar approach to find `figure` with `wp-image` and remove the appended param so things work nicely. 

I can split this one out into a different PR if you'd prefer

**Comment by lawrencegripper** [comment]
> @lawrencegripper there are a few linter issues before this can be merged in

Linting issues should be fixed now :crossed_fingers:

**Comment by ashishb** [comment]
> I hit an issue with img's that where added view the new block editor. The src has ?w=1024 appended which causes the file downloaded to be image.png?w=1024 and this doesn't work with hugo serve.

Huge variance here

> I can split this one out into a different PR if you'd prefer

Yeah, that would be preferable.

**Pull request merged**
